env_name ="databricks"
user_name ="[firstname.lastname]"
region = "ap-northeast-2"
databricks_account_id = "[databricks account id]"
client_id = "[client id of a service principal(having admin permission)]"
client_secret = "[client secret value of the service principal]"
cidr_block = "[vpc cidr block]"
